from typing import Protocol, Optional, List
from shared.ids import UserId, ProductId
from features.memberships.domain.entities import Membership

class MembershipRepositoryPort(Protocol):
    def get(self, user_id: UserId, product_id: ProductId) -> Optional[Membership]: ...
    def add(self, membership: Membership) -> None: ...
    def remove(self, user_id: UserId, product_id: ProductId) -> None: ...
    def list_by_user(self, user_id: UserId) -> List[Membership]: ...

class UserReaderPort(Protocol):
    def exists(self, user_id: UserId) -> bool: ...

class ProductReaderPort(Protocol):
    def exists(self, product_id: ProductId) -> bool: ...
