[tools]
node = "18"

[env]
NODE_ENV = "development"
PORT = "3000"

[tasks.install]
description = "Instala dependencias"
run = "npm install"

[tasks.start]
description = "Arranca la app"
depends = ["install"]
run = "npm start"