version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: ddd_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: AppMunicipality
      TZ: America/Bogota
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
