CREATE TABLE personas (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Category CHAR(1),
    Age INT,
    Description TEXT
);


INSERT INTO personas (Name, Category, Age, Description)
SELECT
  CONCAT(
    CHAR(65 + FLOOR(RAND() * 26)),
    CHAR(65 + FLOOR(RAND() * 26)),
    CHAR(65 + FLOOR(RAND() * 26)),
    CHAR(65 + FLOOR(RAND() * 26))
  ) AS Name,
  ELT(FLOOR(RAND() * 3) + 1, 'A', 'B', 'C') AS Category,
  FLOOR(RAND() * 100) + 18 AS Age,
  CONCAT('Descripción aleatoria número ', FLOOR(RAND() * 1000) + 1) AS Description
FROM
  -- Generamos 10,000 filas con cruces de 10 subconsultas
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) a,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) b,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) c,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) d,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) e,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) f,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) g,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) h,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) i,
  (SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1) j
LIMIT 10000;


EXPLAIN SELECT count(ID) FROM personas WHERE Category = "E";


EXPLAIN ANALYZE FORMAT=TREE SELECT * FROM personas WHERE Category = 'C';

SELECT COUNT(Category) FROM personas WHERE Category = 'C';

EXPLAIN SELECT * FROM personas WHERE Category = 'E';

SELECT * FROM performance_schema.events_statements_summary_by_digest;

CREATE INDEX idx_category ON personas(Category);
ALTER TABLE personas DROP INDEX idx_category;