CREATE DATABASE GESTION_MEDICO;
USE GESTION_MEDICO;


CREATE TABLE RAZA(
    Codr  INT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(250) NOT NULL
);
CREATE TABLE MEDICO(
    Cedm INT AUTO_INCREMENT PRIMARY KEY,
    Nom1 VARCHAR(50) NOT NULL,
    Nom2 VARCHAR(50) NOT NULL,
    Apellido1 VARCHAR(50) NOT NULL,
    Apellido2 VARCHAR(50) NOT NULL,
    Tel VARCHAR(30) NOT NULL,
    Celular VARCHAR(30) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    idEstudios INT NOT NULL,
    CONSTRAINT (idEstudios) FOREIGN KEY ESTUDIO(idEstudio)
);
CREATE TABLE ANIMAL(
    Coda INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Fecha_nac DATETIME NOT NULL,
    Codr INT NOT NULL,
    CONSTRAINT (Codr) FOREIGN KEY Raza(Codr)
);
CREATE TABLE CITA(
    Numc INT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATETIME NOT NULL,
    Coda INT NOT NULL,
    Cedm INT NOT NULL,
    CONSTRAINT (Coda) FOREIGN KEY ANIMAL(Coda),
    CONSTRAINT (Cedm) FOREIGN KEY MEDICO(Cedm)
);
CREATE TABLE ESTUDIO(
    idEstudios INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(50) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    FechaDeGraduacion DATETIME NOT NULL
);