// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYU0LalDjLt4Hif0uRLUIl48jXwA-fJ8',
    appId: '1:303620912037:web:e636f97c379f78fc392e4c',
    messagingSenderId: '303620912037',
    projectId: 'uniremington-pruebas',
    authDomain: 'uniremington-pruebas.firebaseapp.com',
    storageBucket: 'uniremington-pruebas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxLzxdMGXNx0ODYMX9-9DpwWh8RDuO8c',
    appId: '1:303620912037:android:513c70602796a2aa392e4c',
    messagingSenderId: '303620912037',
    projectId: 'uniremington-pruebas',
    storageBucket: 'uniremington-pruebas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4olSpCSvv0n4z4vkaRzEPKjlwUyt6zU',
    appId: '1:303620912037:ios:379207ecda760e4f392e4c',
    messagingSenderId: '303620912037',
    projectId: 'uniremington-pruebas',
    storageBucket: 'uniremington-pruebas.appspot.com',
    iosClientId: '303620912037-8hvetrmafs6bbpo9n2o7liroobn2o7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth2Crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn4olSpCSvv0n4z4vkaRzEPKjlwUyt6zU',
    appId: '1:303620912037:ios:379207ecda760e4f392e4c',
    messagingSenderId: '303620912037',
    projectId: 'uniremington-pruebas',
    storageBucket: 'uniremington-pruebas.appspot.com',
    iosClientId: '303620912037-8hvetrmafs6bbpo9n2o7liroobn2o7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth2Crud',
  );
}
