spring:
  application:
    name: hernandezjimenez-webflux

  r2dbc:
    url: r2dbc:mysql://localhost:3306/app_java
    username: root
    password: root

  # Runs schema.sql on startup for R2DBC
  sql:
    init:
      mode: always

  messages:
    basename: messages
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: alexanderjmz2015@gmail.com
    password: bzlq wcjq phgr yain
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  jwt:
    secret: "MiSecretoMuySeguroCambialoQueSeaDeAlMenos32Caracteres!123456"
    expirationMs: 1200000

logging:
  level:
    root: INFO
    org.springframework.r2dbc: INFO
